name: RNAFlowX CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main


jobs:

  test:

    runs-on: ubuntu-latest


    steps:

      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Install Nextflow
        uses: nf-core/setup-nextflow@v2


      - name: Check Nextflow version
        run:
          nextflow -version


      - name: Run RNAFlowX integration test
        run:
          nextflow run main.nf \
          -config tests/integration/test.config \
          -stub-run
